server:
  port: 8080

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog_database?characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&useSSL=false
    username: root
    password: sa

    #下面为连接池补充设置
    initialSize: 5
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    useGlobalDataSourceStat: true



mybatis:
#  配置xml 的扫描路径
#  mapper-locations: classpath*:org/spring/boot/mapper/*.xml
#  check-config-location: true
#  type-aliases-package: com.maoxiang.springboot_config.entity
  configuration:
#     开启驼峰命名检查
     map-underscore-to-camel-case: true

#通用mapper
mapper:
  mappers: com.maoxiang.springboot_config.Base.MyMapper
  not-empty: false
  identity: MYSQL


#  配置分页插件
pagehelper:
  autoDialect: true
  closeConn: false
  reasonable: true




#日志配置
logging:
#  config:
#日志输出类型
#  pattern:
#    console:"%d - %msg%n"

  #注：二者不能同时使用，如若同时使用，则只有logging.file生效
  #默认情况下，日志文件的大小达到10MB时会切分一次，产生新的日志文件，默认级别为：ERROR、WARN、INFO
  #  path: ../tomcatlogs/
  #  file: ../tomcatlogs/info.log
  #  logging.level：日志级别控制前缀，*为包名或Logger名
  #  LEVEL：选项TRACE, DEBUG, INFO, WARN, ERROR, FATAL, OFF
    level:
     com: debug
#spring:
#  devtools:
#    restart:
#      enabled: true
#      additional-paths: com